### ISSUE TITLE
Why is emitter set to nil on initialize?

### ISSUE THREAD

**Issue by ematpl** [cloudfoundry/dropsonde#1]
https://github.com/cloudfoundry/dropsonde/blob/c9683ed5cab6fa9bceda6e77c74e55cfd09e4f7d/dropsonde.go#L55-L64

Seems unsafe to have a nil pointer reference here.  Why not set the emitter to the `NullEventEmitter` and then, if able to create a proper emitter, setting it to that?

We dereferenced that nil emitter when Diego's inigo integration suite was running with its gorouter's metron address misconfigured. We'll file a separate issue with the gorouter for it not to ignore dropsonde initialization errors, but it seems unsafe for dropsonde to allow itself to get into a bad state.

Thanks,
@Amit-PivotalLabs && Eric

**Comment by jmtuley** [comment]
This was fixed on December 31st, according to the linked Tracker story. I'm closing the issue.
