### ISSUE TITLE
X-Forwarded-For not respected when setting RemoteAddress field for HttpStartStop

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/dropsonde#14]
https://github.com/cloudfoundry/dropsonde/blob/master/factories/factories.go#L71

If you are behind a reverse proxy (likely) this value will be set to the reverse proxy's address and is virtually useless to consumers of this data.

**Comment by Jim-Campbell** [comment]
FIxed in [this story](https://www.pivotaltracker.com/story/show/110509298)
