### ISSUE TITLE
HttpStartStop event sets an invalid URI when X-Forwarded-For is set

### ISSUE THREAD

**Issue by crhino** [cloudfoundry/dropsonde#16]
The fix for #14 looks like it is not setting the RemoteAddress field, but instead sets the [Host portion of the URI](https://github.com/cloudfoundry/dropsonde/blob/master/factories/factories.go#L70) to the value of `X-Forwarded-For` when the header is present. This is incorrect, as the `X-Forwarded-For` contains a comma-separated list of IP addresses.

This results in HttpStartStop events from bosh-lite with uris like:

```
 uri:"http://192.168.50.1, 10.244.0.21/v2/resource_match" remoteAddress:"10.244.0.21:53832"  >
```

One might expect this:

```
 uri:"http://api.bosh-lite.com/v2/resource_match" remoteAddress:"192.168.50.1:53832"  >
```

The question of what to put in the `remoteAddress` field is an interesting one, since the `X-Forwarded-For` header cannot really be trusted to be correct and might be modified. That might not be a concern though, and if support for `X-Forwarded-For` is wanted the last IP address in the list would potentially be the most accurate.

**Comment by nelsam** [comment]
Wow, yeah, our solution isn't correct.  We're fixing it now.

I don't think we're too concerned with the `X-Forwarded-For` header's trustworthiness at this moment.  It's not hugely worrisome if the `RemoteAddress` field of an `HttpStartStop` event can be spoofed.

**Comment by nelsam** [comment]
After a quick discussion, I think we would all prefer to remove our current solution and add a story to add addresses from the `X-Forwarded-For` and probably `Forwarded` headers to the `HttpStartStop` event in a new field, so that consumers can decide which address(es) they care about.  We don't think that we should be making that decision for them.

**Comment by apoydence** [comment]
@crhino This seems to be stale. I'm going to close. Please reopen more is needed.
