### ISSUE TITLE
Add Concourse Badge to README

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/dropsonde#20]
Dropsonde unit tests are being run as part of [this pipeline](https://loggregator.ci.cf-app.com/teams/main/pipelines/loggregator/jobs/dropsonde-unit-tests).

Add a concourse badge to the README to reflect the project's health.

**Comment by AlphaT3ch** [comment]
I think I can handle those. Claiming this issue...

**Comment by wfernandes** [comment]
@AlphaT3ch Thanks. 

Just FYI.

All pull request authors must have a Contributor License Agreement (CLA) on-file with us. Please sign the appropriate CLA (individual or corporate).

When sending signed CLA please provide your github username in case of individual CLA or the list of github usernames that can make pull requests on behalf of your organization.

If you are confident that you're covered under a Corporate CLA, please make sure you've publicized your membership in the appropriate Github Org, per these instructions.

**Comment by AlphaT3ch** [comment]
@wfernandes Thanks for letting me know. Just emailed it in.
