### ISSUE TITLE
New Tag for dropsonde

### ISSUE THREAD

**Issue by winkingturtle-vmw** [cloudfoundry/dropsonde#27]
👋 After [this PR](https://github.com/cloudfoundry/dropsonde/pull/26) was merged, we are unable to get the latest version of this repo, unless we `go get github.com/cloudfoundry/dropsonde@master` which would be a one-time update to the latest SHA. It'd be great if there would be a new tag other than 1.0.0 (e.g 1.1.0 with the same import-path) so that we could get the latest version of this repo. There are [a total of ~40 packages](https://pkg.go.dev/github.com/cloudfoundry/dropsonde?tab=importedby) in code.cloudfoundry.org that is still importing this repo.

**Comment by ctlong** [comment]
Hi @winkingturtle-vmw!

I'm pretty hesitant to add a new tag to / essentially cut a new release for this repo. We consider it deprecated by [go-loggregator](https://github.com/cloudfoundry/go-loggregator), and adding a `v1.1.0` might give the impression that this repo will continue to be maintained moving forward.

If cutting this tag makes your flow significantly easier then I'll do it. I would prefer it if y'all just did the `go get github.com/cloudfoundry/dropsonde@master` path right now though. Just let me know :slightly_smiling_face:

In the long term we'd really like to get cloudfoundry releases off this library.

**Comment by ctlong** [comment]
I tagged master as `v1.1.0`.

**Comment by winkingturtle-vmw** [comment]
Thanks. I realized that I never got back to this issue. Do you need any help to try to track down every CF related tooling that is still using this repo?

**Comment by ctlong** [comment]
No problem. It was easy to do even if it wasn't my preferred option 😄

I think we can track imports down on our own if we ever prioritize moving everyone off this, thanks. If you have free time and want to have a go at removing this library from any Diego or Networking-specific repos that would be awesome though!
