### ISSUE TITLE
Support for customizing Dropsonde metrics interval

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/dropsonde#8]
Ref: https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/RBAVR47B5VGO2JX52FPAEIX42RIYJCQ2/

It is expensive for me to record dropsonde stats every 10 seconds and I cannot think of a good way to limit the frequency of publishing in a clustered nozzle other than depending on some shared state like etcd or something complex like that.

**Comment by erikjasiak** [comment]
Apologies for the delay; closing as per the original thread on the cf-dev list : 
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/FATMPX2Z5HGWS2ANJQDJBBUPFT22AQNU/

Thanks,
Erik
