### ISSUE TITLE
`X-CF-Requestid` header should be `CF-Requestid`

### ISSUE THREAD

**Issue by jchesterpivotal** [cloudfoundry/dropsonde#9]
The `X-` prefix to namespace vendor headers was deprecated in June 2012 by [RFC6648](https://tools.ietf.org/html/rfc6648).

**Comment by jchesterpivotal** [comment]
I see that we also have other such headers -- `x-cf-applicationid`, `x-cf-instanceid`. Again, these should not be using the `x-` prefix.

**Comment by roxtar** [comment]
Apart from being conformant to the RFC which you mentioned, what else do we gain by making this change? I am trying to weigh the benefits against the potential of breaking clients who might rely on the header name.

**Comment by jchesterpivotal** [comment]
It may be too late to correct at this stage.

The RFC pretty much lays out the arguments: it's unnecessary, it doubles code paths (for `X-foo:` and `foo:` and basically just produces pollution).

I was not aware we were deeply into production on these headers, last I looked we were using `vcap-*` for things.

**Comment by roxtar** [comment]
@jchesterpivotal I agree that it might be a little late to correct. The risks of making this change outweigh the benefits. Thanks for bringing this to our attention. We will keep this in mind for any future custom headers which we add. But for now, I am closing this issue.
